=== XenoDT/vscode/LenguajeMarcas/Ejs/xml/EjsClase/pc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://tierno.es/pc"
    xmlns:tns="http://tierno.es/pc"
    elementFormDefault="qualified">
    <xs:element name="pc">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="processor">
                    <xs:complexType>
                        <xs:attribute name="brand" type="xs:string" />
                        <xs:attribute name="hz" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="keyboard">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="lang" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="speaker" type="tns:TypeSpeaker"/>
                <xs:element name="ram-slots">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ram" type="xs:int" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="type" type="tns:RamType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="screen" type="tns:TypeScreen"/>
                <xs:element name="display" type="tns:TypeScreen"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="RamType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DDR5"/>
            <xs:enumeration value="DDR4"/>
            <xs:enumeration value="DDR3"/>
            <xs:enumeration value="DDR2"/>
        </xs:restriction>
    </xs:simpleType>

     <xs:complexType name="TypeScreen">
        <xs:sequence>
            <xs:element name="inches" type="xs:string" />
            <xs:element name="resolution" type="xs:decimal" />
        </xs:sequence>
    </xs:complexType>

     <xs:complexType name="TypeSpeaker">
        <xs:all>
            <xs:element name="material">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="metal" />
                        <xs:enumeration value="plastic" />
                        <xs:enumeration value="other" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="power">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="2" />
                        <xs:maxInclusive value="10" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== XenoDT/vscode/LenguajeMarcas/Ejs/CSS/xml/EjsClase/pc.xml
<?xml version="1.0" encoding="UTF-8"?>
<pc xmlns="http://tierno.es/pc"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tierno.es/pc pc.xsd">
    <processor brand="intel" hz="5Ghz"></processor>
    <keyboard lang="es">Logitech</keyboard>
    <speaker>
        <power>2</power>
        <material>plastic</material>
    </speaker>
    <ram-slots type="DDR5">
        <ram>6</ram>
        <ram>8</ram>
    </ram-slots>
    <screen>
        <inches>19.1</inches>
        <resolution>5</resolution>
    </screen>
    <display>
        <inches>4</inches> 
        <resolution>2</resolution>
    </display>
</pc>
