=== XenoDT/vscode/LenguajeMarcas/Ejs/xml/EjsClase/uni_lib.dtd
<!ELEMENT university_library (department+,library_services)>

<!ELEMENT department (course+)>
<!ELEMENT library_services (service+)>

<!ELEMENT course (course_name,required_textbooks,recommended_readings)>
<!ELEMENT required_textbooks (textbook+)>
<!ELEMENT course_name (#PCDATA)>
<!ELEMENT textbook (title,authors,edition,publisher,year,library_copies)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT library_copies (#PCDATA)>
<!ELEMENT recommended_readings (online_resource)>
<!ELEMENT online_resource (title,url)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT service (service_name,available_to,max_items_per_month,fee)>
<!ELEMENT service_name (#PCDATA)>
<!ELEMENT available_to (#PCDATA)>
<!ELEMENT max_items_per_month (#PCDATA)>
<!ELEMENT fee (#PCDATA)>
<!ATTLIST department
    name CDATA #REQUIRED
    code ID #REQUIRED
>
<!ATTLIST course
    course_id ID #REQUIRED
>
<!ATTLIST textbook
    isbn CDATA #REQUIRED
    format (physical | digital) #REQUIRED
>
<!ATTLIST library_copies
    total CDATA "0"
    available CDATA "0"
    reserved CDATA "0"
>
<!ATTLIST online_resource 
    access_type CDATA "free"    
>
<!ATTLIST service
    service_id CDATA "something"
>
<!ATTLIST fee 
    currency (EUR|USD|LB) "EUR" 
>
<!ENTITY library-name "City Central Library">
<!ENTITY default-currency "EUR">

=== XenoDT/vscode/LenguajeMarcas/Ejs/xml/EjsClase/university_library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE university_library SYSTEM "uni_lib.dtd">

<university_library>
  <department name="Computer Science" code="CS">
    <course course_id="CS101">
      <course_name>Programming Fundamentals</course_name>
      <required_textbooks> <!-- puede haber muchos -->
        <textbook isbn="978-0131103627" format="physical">
          <title>The C Programming Language</title>
          <authors>
            <author>Brian W. Kernighan</author>
            <author>Dennis M. Ritchie</author>
          </authors>
          <edition>2nd</edition>
          <publisher>Prentice Hall</publisher> <!-- opcional -->
          <year>1988</year> <!-- opcional -->
          <library_copies total="15" available="3" reserved="5" /> <!-- valores por defecto a 0 en los 3-->
        </textbook>
      </required_textbooks>
      <recommended_readings>
        <online_resource access_type="free"> <!-- valores yes o no--> 
          <title>Python Tutorial for Beginners</title>
          <url>https://docs.python.org/3/tutorial/</url>
        </online_resource>
      </recommended_readings>
    </course>
  </department>

  <library_services>
    <service service_id="interlibrary">
      <service_name>Interlibrary Loan</service_name>
      <available_to>all_students</available_to>
      <max_items_per_month>10</max_items_per_month>
      <fee currency="EUR">0.00</fee>
    </service>
  </library_services>
</university_library>
