=== XenoDT/vscode/LenguajeMarcas/Ejs/CSS/xml/EjsClase/film_catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://tierno.es/film_catalog"
    xmlns:tns="http://tierno.es/film_catalog"
    elementFormDefault="qualified">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie" type="tns:TypeMovie" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>      
    </xs:element>
    <xs:complexType name="TypeMovie">
        <xs:sequence>
            <xs:element name="title"/>
            <xs:element name="year"/>
            <xs:element name="genre" maxOccurs="3"/>
            <xs:element name="rating" minOccurs="0"/>
            <xs:element name="director">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="nationality"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="duration"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== XenoDT/vscode/LenguajeMarcas/Ejs/CSS/xml/EjsClase/flim_catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  REQUISITOS para el XSD:
  - Elemento raíz: "catalog"
  - Cada película debe tener: title (obligatorio), year (entre 1900-2024)
  - Genre: lista de valores fijos (action, comedy, drama, sci-fi)
  - Clasificación por edades (rating): opcional, valores: PG, PG-13, R, NC-17
  - Director: puede tener atributo "nationality" (opcional)
  - Duration: número positivo en minutos
  - PUNTUACIÓN EXTRA: Usar xs:all en vez de xs:sequence
-->
<catalog xmlns="http://tierno.es/film_catalog"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tierno.es/film_catalog film_catalog.xsd">
    <movie>
        <title>El Padrino</title>
        <year>1972</year>
        <genre>drama</genre>
        <rating>R</rating>
        <director nationality="estadounidense">Francis Ford Coppola</director>
        <duration>175</duration>
    </movie>
    <movie>
        <title>Regreso al Futuro</title>
        <year>1985</year>
        <genre>sci-fi</genre>
        <genre>comedy</genre>
        <director nationality="EU">Robert Zemeckis</director>
        <duration>116</duration>
    </movie>
</catalog>
