=== XenoDT/vscode/LenguajeMarcas/Ejs/CSS/xml/EjsClase/hotel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://tierno.es/hotel"
    xmlns:tns="http://tierno.es/hotel"
    elementFormDefault="qualified">
    
    <xs:element name="bookings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="booking" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="checkinDate" type="xs:date"/>
                            <xs:element name="checkoutDate" type="xs:date" />
                            <xs:element name="guest">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="email" type="xs:string" />
                                        <xs:element name="phone" type="xs:integer" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="roomType" type="tns:RoomType"/>
                            <xs:element name="service" maxOccurs="unbounded" type="xs:string"/>
                            <xs:element name="totalPrice" type="xs:decimal" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="RoomType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="indidual"/>
            <xs:enumeration value="doble"/>
            <xs:enumeration value="suite"/>
            <xs:enumeration value="familiar"/>
        </xs:restriction>
    </xs:simpleType>
     <xs:simpleType name="ServiceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="desayuno"/>
            <xs:enumeration value="spa"/>
            <xs:enumeration value="parking"/>
            <xs:enumeration value="familiar"/>
        </xs:restriction>
    </xs:simpleType
</xs:schema>

=== XenoDT/vscode/LenguajeMarcas/Ejs/xml/EjsClase/hotel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  REQUISITOS para el XSD:
  - Elemento raíz: "bookings"
  - Puede haber varios elementos booking.
  - Cada reserva debe tener ID (formato: RES-XXXX donde X es dígito)
  - Fechas (checkinDate y checkoutDate): entrada y salida (formato fecha ISO: YYYY-MM-DD)
  - Huésped (guest): name (obligatorio), email (validar formato email), phone (opcional)
  - Tipo de habitación (roomType): valores fijos (individual, doble, suite, familiar)
  - Servicios adicionales: lista (puede repetirse): desayuno, spa, parking, gym
  - Precio total: decimal con 2 decimales, mínimo 50.00
  - Bonus: Validar que fechaSalida > fechaEntrada
-->
<bookings xmlns="http://tierno.es/hotel"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tierno.es/hotel hotel.xsd">
    <booking id="RES-1001">
        <checkinDate>2024-06-15</checkinDate>
        <checkoutDate>2024-06-20</checkoutDate>
        <guest>
            <name>María López</name>
            <email>maria.lopez@email.com</email>
            <phone>+34600123456</phone>
        </guest>
        <roomType>doble</roomType>
        <service>breakfast</service>
        <service>parking</service>
        <totalPrice>450.00</totalPrice>
    </booking>
    
</bookings>
